# Generated by Django 4.2.3 on 2023-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha'),
        ),
    ]
