# Generated by Django 4.2.3 on 2023-08-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('genero', models.CharField(blank=True, max_length=50, null=True, verbose_name='genero')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('local_nascimento', models.TextField(blank=True, null=True, verbose_name='Naturalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='idade')),
                ('cpf', models.IntegerField(blank=True, null=True, verbose_name='CPF')),
                ('altura', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('peso', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('sexo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('senha', models.CharField(blank=True, max_length=200, null=True, verbose_name='senha')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tela1.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do pedido')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('tempo_de_espera', models.TimeField(blank=True, null=True, verbose_name='Tempo de espera')),
                ('total_a_pagar', models.FloatField(blank=True, null=True, verbose_name='Total a pagar')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tela1.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo')),
                ('ano_lancamento', models.DateField(blank=True, null=True, verbose_name='Ano de lançamento')),
                ('genero', models.CharField(blank=True, max_length=200, null=True, verbose_name='genero')),
                ('numero_de_faixas', models.PositiveIntegerField(blank=True, null=True, verbose_name='numero de faixas')),
                ('tempo_de_musica', models.FloatField(blank=True, null=True, verbose_name='Tempo de Musica')),
                ('artista', models.ManyToManyField(to='tela1.artista')),
            ],
        ),
    ]
