# Generated by Django 4.2.3 on 2023-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='idade')),
                ('cpf', models.IntegerField(blank=True, null=True, verbose_name='CPF')),
                ('altura', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('peso', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido'), ('N/C', 'Não Consta')], max_length=100, null=True, verbose_name='Sexo')),
            ],
        ),
    ]
