# Generated by Django 4.2.3 on 2023-08-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo'),
        ),
    ]
