# Generated by Django 4.2.3 on 2023-08-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
