# Generated by Django 4.2.3 on 2023-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela1', '0007_alter_cargo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo')),
                ('ano_lancamento', models.DateField(blank=True, null=True, verbose_name='Ano de lançamento')),
                ('genero', models.CharField(blank=True, max_length=200, null=True, verbose_name='genero')),
                ('numero_de_faixas', models.PositiveIntegerField(blank=True, null=True, verbose_name='numero de faixas')),
                ('tempo_de_musica', models.FloatField(blank=True, null=True, verbose_name='Tempo de Musica')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('genero', models.CharField(blank=True, max_length=50, null=True, verbose_name='genero')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('local_nascimento', models.TextField(blank=True, null=True, verbose_name='Naturalidade')),
            ],
        ),
    ]
