# Generated by Django 4.2.3 on 2023-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela1', '0008_album_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ManyToManyField(to='tela1.artista'),
        ),
    ]
