# Generated by Django 4.2.3 on 2023-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('idade', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Idade')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('endereço', models.TextField(blank=True, null=True, verbose_name='Endereço')),
            ],
        ),
    ]
