# Generated by Django 4.2.3 on 2023-08-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Zé Roberto', max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('idade', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Idade')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('endereço', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telas.cargo', verbose_name='Fcargo')),
            ],
        ),
    ]
