# Generated by Django 4.2.3 on 2023-08-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_pessoa', models.FileField(upload_to='fotos')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('senha', models.CharField(blank=True, max_length=200, null=True, verbose_name='Senha')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corpo.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pedido')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantiade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Tempo estimado para entrega')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corpo.pessoa')),
            ],
        ),
    ]
