# Generated by Django 4.2.3 on 2023-07-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('data_criacao', models.DateField(auto_now=True, verbose_name='Data da criacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evento',
                'unique_together': {('titulo', 'data_criacao')},
            },
        ),
    ]
